apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: livraria-api
  annotations:
    github.com/project-slug: talesrc/livraria-api
    backstage.io/kubernetes-id: livraria-api
    backstage.io/techdocs-ref: dir:./README.md
spec:
  type: service
  lifecycle: dev
  owner: taleco
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    # client:
    #   title: Cliente
    #   type: string
    #   description: Cliente
    #   ui:widget: cliente
    #   default: tecsinapse
    #   enum:
    #     - tecsinapse
    #     - mercedes
    #     - bajaj
    # stage:
    #   title: stage
    #   type: string
    #   description: stage
    #   ui:widget: stage
    #   default: "dev"
    #   enum:
    #     - prod
    #     - homolog
    #     - dev
    # cpu_request:
    #   title: cpu_request
    #   type: string
    #   description: cpu_request
    #   ui:widget: cpu_request
    #   default: "0.1"
    # cpu_limits:
    #   title: cpu_limits
    #   type: string
    #   description: cpu_limits
    #   ui:widget: cpu_request
    #   default: "0.1"
    # memory_request:
    #   title: memory_request
    #   type: string
    #   description: memory_request
    #   ui:widget: memory_request
    #   default: "0.1"
    # memory_limits:
    #   title: memory_limits
    #   type: string
    #   description: memory_limits
    #   ui:widget: memory_limits
    #   default: "0.1"
