version: '3.7'

services:

    appDB:
      image: mariadb
      container_name: appDB
      environment:
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_DATABASE=LIVRARIA
      ports:
        - 3306:3306
    