version: '3.7'

services:
    db:
      image: mariadb
      container_name: livraria_db
      environment:
        MARIADB_ROOT_PASSWORD: 
        MARIADB_DATABASE: LIVRARIA
      ports:
        - 3306:3306
